### ISSUE TITLE
Win32mica error

### ISSUE THREAD

**Issue by brakheart** [Djdefrag/Fapello.Downloader#1]
When trying to download from a link, this message pops up:
![imagen](https://user-images.githubusercontent.com/26739575/209967430-68df0817-8345-400b-bb4f-c9d46d14de60.png)

I'm assuming it's because of my Windows version, since I have the 19045. Is there any way to fix this? Like running it on an older Windows version? (Already have Windows updated to the latest version)

**Comment by Djdefrag** [comment]
Hi @brakheart, 

the Win32Mica Error is just a warning for the transparent effect on the background because it is only compatible with Windows 11, probably you have Windows 10, right? :)

There was a bug when selecting Firefox or Edge as browser, i just released a fix with other improvements too :D

**Comment by brakheart** [comment]
Yes, I have Windows 10. But still, it didn't download anything from the link. 
I just deleted the folder and redownloaded it along with the necessary files from the requirements .txt and it works perfectly now!
Thank you

**Comment by Djdefrag** [comment]
Nice! :D
