### ISSUE TITLE
"ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by brakheart** [Djdefrag/Fapello.Downloader#16]
When trying to open the program on CMD it shows that error message. See image:
![2024-12-04_12-06](https://github.com/user-attachments/assets/7100740a-1ac8-4c53-ad1a-913766d45c60)

Am i missing some configuration or something? Also, when trying to open it by doubleclicking the .py it opens and closes automatically.

**Comment by Djdefrag** [comment]
Hi my friend,

have you installed dependencies listed in requirements.txt?

you should install them with 

`pip install -r requirements.txt`

**Comment by brakheart** [comment]
aaah i hadn't done that, since it's not in any of the steps in the readme. Thank you! it works now
