### ISSUE TITLE
Downloading Dupe

### ISSUE THREAD

**Issue by iGetUploaded** [Djdefrag/Fapello.Downloader#2]
So I was testing this to see if it would actually work and when it started to download the pictures/videos it downloaded them twice not sure if its something im doing or what

**Comment by Djdefrag** [comment]
Hi my friend, this is strange.
Did you checked that maibe in the selected fapello page there are multiple photos that are the same?

**Comment by iGetUploaded** [comment]
Hello srry for late response I checked it multiple times even had a buddy try it and it did the same for him

**Comment by Djdefrag** [comment]
This is super weird D: 

Do these doubled files have the same name and extension (.jpg / .png)?

**Comment by iGetUploaded** [comment]
They have the same name so it would be like this example [fistname-lastnme_number].png

**Comment by iGetUploaded** [comment]
Update I did get it to work now I just redownloaded it and tried again.. Not sure what was going on with it
